services:
  crawl4ai:   # Simplified service name
    image: unclecode/crawl4ai:${VERSION:-basic}-amd64
    ports:
      - "11235:11235"
      - "8025:8000"
      - "9222:9222"
      - "8065:8080"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
